# -*- coding: utf-8 -*-
"""asn2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14VqA0YQcfISQBWQN1L-oPymyV6DvjV7g
"""

# Student name:
# Student ID:

import math
import csv
import numpy
from termcolor import colored


def load_asn2_data():
  """
  This function loads the file `wordle.csv` and returns a LIST of 5 letters words.
  We'll talk about LISTs formally in class in a few lectures, but maybe
  you can start guessing how they work based on what you see here...
  """
    
    
  reader = csv.reader(open('./wordle.csv', 'r'))        # wordle.csv MUST be in the same directory as this script for this to work!
  words = []  
  
  for r in reader:
    words.append(r[0]+r[1]+r[2]+r[3]+r[4])
        
  return words

def color(char, color):
  """
  This function return a char in color.
  """
  if color == 'ORANGE':
    return '\033[93m' + char
  elif color == 'GREEN':
    return '\033[92m' + char
  else:
    return '\033[0m'+char

def choose_a_word(list_of_words):
  """
  This function choose a word randomly from a list of word.
  """
  # INSERT YOUR CODE HERE

def give_hint(player_guess, word_to_guess):
  """
  This function gives hint to the user.
  Print the hints directly.
  """
  hints = ""

  # INSERT YOUR CODE HERE

  print(hints)
  print('\033[0m')

def guess_word(word_to_guess):
  """
  This function as the player a word until they found the word or they guessed 5 times.
  Return True if the word is found, or False otherwise.
  """
  nb_guess = 0

  # INSERT YOUR CODE HERE

def wordle():
  """
  This is the main function.
  This function load the data file, choose a word to guess and launch the game.
  """

  # INSERT YOUR CODE HERE

wordle()